
#!/usr/bin/python3

"""
Module to extract TROPOMI data for a specified location.

This script uses the Sentinel API to download TROPOMI data for a given location and time range.
It processes the data and saves the results as a CSV file.

This script looks for centroids of grid cells already generated by the OSMExtractor.



"""


import os
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
import numpy as np
from datetime import datetime, timedelta
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from tqdm import tqdm



class TROPOMIExtractor:
    def __init__(self, city_name, start_date, end_date, cell_size=100, output_file="data/tropomi_data.csv"):
        self.city_name = city_name
        self.start_date = start_date
        self.end_date = end_date
        self.cell_size = cell_size
        self.output_file = output_file
        self.api = SentinelAPI('username', 'password', 'https://scihub.copernicus.eu/dhus')
        self.grid_gdf = None

    def load_grid_centroids(self):
        """
        Load the grid centroids from the OSMExtractor output file.
        """
        print("Loading grid centroids...")
        self.grid_gdf = gpd.read_file(self.output_file)